config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'http#http_post'
  post 'http_post' => 'http#http_post'
  get 'http_post' => 'http#http_post'

  match '/destroy_them_all', to: 'http#destroy_them_all', via: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/xml.rb
class Xml < ApplicationRecord
  require "rexml/document"
  require "json"

  def self.format_data(data)
    if valid_json?(data)
      JSON.parse(data)
      return data
    end
    begin
      @doc = REXML::Document.new(data)
      @out = ""
      @doc.write(@out, 1)
      return @out
    rescue
      return "Invalid Data"
    end
  end

  private
  def self.valid_json?(json)
      JSON.parse(json)
      return true
    rescue JSON::ParserError => e
      return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/http_controller.rb
class HttpController < ApplicationController
  skip_before_action :verify_authenticity_token

  def http_post
    @xml_body = request.body.read
    if @xml_body.present?
      @xml = Xml.create(:xml_body => @xml_body)
    end
    @xmls = Xml.all.sort.reverse
  end

  def destroy_them_all
    Xml.destroy_all
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/http_helper.rb
module HttpHelper
end

app/views/http/http_post.html.erb
<h3>Payload data</h3>
<br>
<%= link_to "Clear Database", destroy_them_all_path, method: :delete, class: "button" %>
<h2>All requests should be posted to: <a href='#'><application url>/http_post</a> </h2>
<% @xmls.each do |data| %>
  <hr>
  <div class="xml-body">
    <h5>payload id: <%= data.id %></h5>
    <h6>created at: <%= data.created_at.strftime("%Y %m %d") %></h6>
    <pre><%= Xml.format_data(data.xml_body) %></pre>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRequestBin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>